### ISSUE TITLE
Hackatone-01 Week-1

### ISSUE THREAD

**Issue by Ftlka** [urfu-2017/team5#15]
# Deadline: 24.03 12:00
В идеале хотелось бы получить уже работающее приложение. Где api, база данных, авторизация через гитхаб, вёрстка, из которой можно отправлять данные. Всё соединено между собой. Баги, костыли, фичи, дизайн - на потом. Сейчас главное, чтобы всё работало.
- [x] @Dan1elNeal доделать авторизацию через github;

- [x] @whoe научиться генерить аватарки. Насколько понимаю, они должны быть симметричными и размера 5x5;

- [ ] @snoward разобраться с сокетами;

- [ ] @danmerus запуллить текущий апстрим и сделать пуллреквест с вёрсткой, чтобы в нём можно было отписываться по реализации. Окно профиля

- [ ] @akulin запросы к серверу при начальном логине, получение списка доступных контактов, добавление новых контактов;

- [ ] @darl0ck сделать пример запуска приложения, вкрутить вёрстку в next.js для отображения;

- [ ] @ftlka отревьюить вёрстку, аналогично подключить её в next.js, разобраться с проблемами, если возникнут.

**Comment by whoe** [comment]
На гите 5x5 аватарки. [Identicons](https://blog.github.com/2013-08-14-identicons/)

**Comment by Ftlka** [comment]
@whoe отредактировала, спасибо :)
